name: zotero # you probably want to 'snapcraft register <name>'
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Single-line elevator pitch for your amazing snap # 79 char long summary
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  zotero:
    command: zotero
    plugs:
      - x11
      - network
      - browser-support
      - wayland
      - opengl
      - home
      - gsettings
      - desktop
    environment:
      XDG_DATA_DIRS: $SNAP/share:$XDG_DATA_DIRS

environment:
  XDG_DATA_DIRS: $SNAP/share:$XDG_DATA_DIRS

parts:
  copy-source:
    # See 'snapcraft plugins'
    plugin: dump
    source: Zotero_linux-x86_64
    
  add-dependencies:
    plugin: nil
    stage-packages:
      - libice6
      - libsm6
      - libx11-xcb1
      - libx11-6
      - libxau6
      - libxcomposite1
      - libxcursor1
      - libxdamage1
      - libxdmcp6
      - libxext6
      - libxfixes3
      - libxi6
      - libxinerama1
      - libxrandr2
      - libxrender1
      - libxt6
      - libatk1.0-0
      - libatk-bridge2.0-0
      - libatspi2.0-0
      - libcairo2
      - libcairo-gobject2
      - libdatrie1
      - libdbus-glib-1-2
      - libepoxy0
      - libfontconfig1
      - libgdk-pixbuf2.0-0
      - libgdk-pixbuf2.0-common
      - libgraphite2-3
      - libgtk-3-0
      - libharfbuzz0b
      - libpango-1.0-0
      - libpangocairo-1.0-0
      - libpixman-1-0
      - libpng16-16
      - libthai0
      - libxcb1
      - libxcb-shm0
      - libxcb-render0
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - light-themes
      - dmz-cursor-theme
      
plugs:
  gtk-3-themes:
    interface: content
    target: $SNAP/share/themes
    default-provider: gtk-common-themes:gtk-3-themes
  icon-themes:
    interface: content
    target: $SNAP/share/icons
    default-provider: gtk-common-themes:icon-themes
  sound-themes:
    interface: content
    target: $SNAP/share/sounds
    default-provider: gtk-common-themes:sounds-themes
